Add PIE
Android 5 requires that files support position independent executables otherwise the following error occurs:
error: only position independent executables (PIE) are supported.
Add PIE flags to CFLAGS and LDFLAGS